# Generated by Django 2.0.6 on 2018-06-28 17:54

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, upload_to=profiles.models.profile_photo_upload_handler),
        ),
    ]
