# Generated by Django 2.0.6 on 2018-07-02 13:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndoorBoulderAscent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('ascent_type', models.CharField(choices=[('SN', 'Send'), ('FL', 'Flash'), ('ON', 'Onsight'), ('RE', 'Repeat')], default='SN', max_length=2)),
                ('grade', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndoorRouteAscent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('ascent_type', models.CharField(choices=[('RP', 'Redpoint'), ('FL', 'Flash'), ('ON', 'Onsight'), ('RE', 'Repeat')], default='RP', max_length=2)),
                ('grade', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
